[package]
name = "RustCrack"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
sha2 = "0.10.8"
sha1 = "0.10.6"
md5 = "0.7.0"
cudarc = {version ="0.16.4", features = ["cuda-version-from-build-system"]}
